--- 
abstract: A POE filter wrapped around Compress::Zlib
author: 
  - Chris Williams <chris@bingosnet.co.uk>
build_requires: 
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-Zlib
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Compress::Zlib: 1.34
  POE: 0.38
  POE::Filter: 0
version: 1.94
