author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Filter::Zlib
name: POE-Filter-Zlib
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Compress::Zlib: 1.34
  POE: 0.3501
version: 1.8
