# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-Zlib
version:      1.2
version_from: lib/POE/Filter/Zlib.pm
installdirs:  site
requires:
    Carp:                          0
    Compress::Zlib:                1.34
    POE:                           0.3501

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
