---
abstract: 'A POE filter wrapped around Compress::Zlib'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-Zlib
no_index:
  directory:
    - inc
    - t
provides:
  POE::Filter::Zlib:
    file: lib/POE/Filter/Zlib.pm
    version: 2.02
  POE::Filter::Zlib::Stream:
    file: lib/POE/Filter/Zlib/Stream.pm
    version: 2.02
requires:
  Compress::Raw::Zlib: 2
  POE: 0.38
  POE::Filter: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-zlib/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-zlib.git
version: 2.02
